language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RT2G8/cLutMJLAr0bWSSaYDHoQpL5NNAtEi72YQHdl1G/4N30xJiuzw65aoxUnm7ewpKKys3YnFblbJCeLe4CUNfxMm4SrIkJd2oEVGdV5U0eBcXeXBff89pcIdqQ6U5keltgwNKdiw/PAxfvKTNPNrgqtJr1xL8gdu1XgLkVGO2CsLuytkusfaH+jv53uM6UzFZwZYtUVp8X9CigTlpFGKKIB4EN525M1M9mj42BbJ888VTfuCkBpEWXK1ePBlK2HKQXRaRWt01BQ+aKzqNR/Xdi66RKAjFkdi0WbyNetZVJtnOalRhUV7lpCiTCmjQhjt1ldBXpjY2Mq27vylMe54MyfDYgVzeRDkCO/dWTdpueyBTsteBYairBhXeIcZ9mLzahXB3SkRErfGMJwNCkNNxnHBku3nrv3150UppmzOEl9sZXht7D26Ikjqhxk5saabiRDUuD5vlvXbXZ+HbQB0UIYp1PHuX656I8Myh/o5bgxdXgotSFa97rP+tlaoc6ITip/LsAAbwbiNkNF66jlFGUFtn9TcMUsGMDUJk2H9U3iY9ohFHyEOcs2vpQbjFxr6B9SoB4wMCzcHqNH/TbaVRtP/9isGMR/TY5IMPEhcd+DT0iSW1V+DhMN4ur/x+HuNSRvN1Lp3fOWs5v8BBTtOfO6N1SMYQTwZdXmkNzHk=
  file:
    - "mdast-util-to-nlcst.js"
    - "mdast-util-to-nlcst.min.js"
  on:
    tags: true
